---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: default-openstack-credential
  namespace: az-test-tenancy
spec:
  encryptedData:
    clouds.yaml: AgAD10f9I2B+neMHKeHbFOMW5/F45f/EUzKkOPMyMIMQ5HkkwfFS7TExMpnlDZ+VHSkosGW18smNtFkXnDG0pmXjDJPUdi1oAlaqj9JvBKFMhVoNUeavTlj7Gh3q8cWQXv4hj/kfq1BneTItc2uots5xNgZYTyPdi3AZFETnIV/Xj9lhVudeVtBHmeE4SJ9KTaH6nqF9E+igOOIYzIWtYIMHiPFW7NVfMK/mlohXXulM8+vxjsd5HpLsf3f89abCa0GpyVBQObYhsL9l4BZLc8mb4L1RPR1D79SWXszSZLPdVQN9NQM3Nc6oej37pas++bl9wmgdnQ9d/25MHXXBgVmyVYj5Tom1J6asdOT4lghB/98y2UETtq4n3NYvEUNbzKmR9SygGvxWgeDt3qZJAI3GJhinNjpn6U4FNJaI6cplXgAKYKAuhRG3w7N4kSdFgds7qw9161udqXJkH73uBDi3W271ZNc5T7Xr2cowPulmr4QSvOuvjVEY+nDrV6+MYEM8MtaLcLMTXKAxxDft958h3nLFupHcG/D58BjQfp0IA7THx8Xd3hj8GHmYT2fMuQHZDM87iF+/4tXwL0LR88iTzXqX9cJ01IwTZmiVgg1xL+akHQ3xpurXM29/20zXcZKZkUd2UNVIH+NDZ8zA4zctz4IHD/jSGglZORjXGburTRrQn+hLuLXPZ+z1IDxkrxIvv9bcdZzLEp2ENo6qKl+N6/NMmm8W2suK/uBdQ30vjkjgYgYauYE+UfbKJdvaHLYNbi3/TbIdy1BP2IAv9aJagZqwDnRX1paBFtOH35t30MuJrToyRiNW1MIyC/Um+hV6f0KILr8sVnOjrh4vWOa1PTCecvm6uTGX44kzfE8FkQFrIZf4oiBnnplSYrC3s011ARUT+PrmvV07NyKuq/S4le6FEDt1D+BkahsXeCJTSwJaIxp9DL3G5HUFSytQeWWV6pHA21+GZUGdbhA0MyrZKsfSLe1k02lZzDzAS7gQp2vLcqDfBJPsPwzP4w4nXyr8D/ynH4yocFoCPKwFmVJPzlS7Vhr3dbebNoztQQ/8RF/APjru1gSiOPdpNj62QR0dOnYVe0GburGarB7UfRfPU1b5Tohy53/tZYtAaU4KFGTh52kwR15tNNoivEP5VahRjNaHmk+hkZD51Ca9BQJaW5CXwHlH1IZ9/RUlcMBTpgKkmrN4WoYpyVeBFwpY8VKkz2SarSVNPOC+
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      creationTimestamp: null
      labels:
        credential.azimuth-cloud.io/provider: openstack
      name: default-openstack-credential
      namespace: az-test-tenancy
