---
apiVersion: user.keycloak.crossplane.io/v1alpha1
kind: User
metadata:
  name: scripted-tenancy-admin
spec:
  forProvider:
    realmId: azimuth-users
    username: wtripp180901
    email: will.tripp@btinternet.com
  providerConfigRef:
    name: keycloak-config
---
apiVersion: user.keycloak.crossplane.io/v1alpha1
kind: Groups
metadata:
  name: scripted-tenancy-admin-group-mapping
spec:
  forProvider:
    realmId: azimuth-users
    userIdRef:
      name: scripted-tenancy-admin
    groupIdsRefs:
      - name: scripted-tenancy
  providerConfigRef:
    name: keycloak-config
