---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: default-openstack-credential
  namespace: az-test-tenancy
spec:
  encryptedData:
    clouds.yaml: AgAxaJcaCxZyvIeSJ6iqVQ9I5me/6oQNrqfA88+ylwpQT2xzKElfadAHoRIEJKs0waU/BTPFmeIBZj/ZxAaw1STmNc6pnbIpVbUHf/Rlx2yzNJfZEcPdnMLTpSnD6SSaLJjN6o/C+lxim2ZUe9J7hOUd8HRDfoB84JJgev5+rsYvexqZiDPVblpNEhw3ooIyIYfEOCjHxdGhWON1Ly68HrRh9SCYoR2BCPe6SLAcZT/60PUGxnQsLmeKGK3rh2fDRuSc+kyyQ3zvGNT+oNeyNiApPDQWxMSQvZqqX3fZvM5NRPttzhW8mHsxpdqsdOuIODa6l892ORIqx6scbqtwBJqsPJNMYZHU0wWhxh8L993oHYk+HtL61eBXVfDtpIEndQ1hGFVpC8kXmP7iZOWF/vdDTd+GZw0Ap5HEQmjdxaa/h1HSgHLSB9ZqTYhE2KOlRsZN5/clDn5ozEa2I2OtEuUngi+FXUWiOfThc16OuIVbGAmga2Hj8vjy1xjQlaZ5AzNNhDsdQQO6l3VKg48AhnkpbRFN40wdBNA87qI1VtQwDfiFSW7YN+6Bs4rsk+7WjkLTRhVjcgkixonfcESXFxZSqVq3Xk4j3oCoUnirTMeOJ4woUu76T9TWKIxxhNgFj5Prya/o21M7ZyEDUCM+Eobs19xA+Z/NFyN8TUGplnjSsm+ES5MAUCl5ZU1T2bsyrKNx9CVXuPCWRthtSYm4qDez12CJ180DSNt3T7KWkMAi+0ZsyyVk5iteaZ4+wfQ0Q+VwzwoJmmdIEi/XYEo1yqVqEU5DSO9G7Hzbp8jGae8e+6KQTJpVqi0lURy9eX+e9LN1Gf3Ly2nYSvOV6ycbPhdrwQsRSzU6at1tFHV4EoyPO/5l/DqwAhyK4yzDCTzyu2NxKwXvA69Sz05MiqmVJpamZX0uoNXcvBMGdtwYoMFv3EDz5Z3azW8voV8lQCE+nVeGz9NxppY8eVRvEs38Pw4EqU+hekiNHRzID5J1apjr9XujkVuopuETlc+WqOlWDf92sqRJ3rkYkVw/+/WkIJqO+I3WGDGR9yGgMk9c09RMT9kjyargLWfkZ+8YYJIe6uwIYxMXHvLjRQ24RVTSOUB5fGtFFOEGCKsaAXB4tTp7Jl5z/80qRp+ota7BUj34+fET8Ri0h/cFEh6X4AZkQ8BD9Asg4zAYoLAt5rnWyYnYR0ANXzijCYEemTjqKhyAkCyIv8BNZyxKPy/0OK6P+FGq+cpYI223
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      creationTimestamp: null
      labels:
        credential.azimuth-cloud.io/provider: openstack
      name: default-openstack-credential
      namespace: az-test-tenancy
