---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: default-openstack-credential
  namespace: az-test-tenancy
spec:
  encryptedData:
    clouds.yaml: AgA+2fSz4pWOqqb6GTcfYMZW1dWb4Ty7PRhoEOHZRWaBDd9J57MtE8Hpymo7mqFkro6p3CmmmopJBmDilawEhVa4Qwkkuxi+BY6A2AihaCDx09S2IU93MctYMfobBqHUWujFkaOV96IaZV0pmmTmyMWCR0Bg9cMjMtK06x1QadtMH9cBCLPNBUbGm08BLtyGBEAqZEGVDHoNRXzYkPc1Zb1o+O+NZ8SKdvzKbaYagSK10D0o5EDufRBzKwtMkKxriD49kbWAHsmsSk2R397CrUqfOrQsH4B6y/pYVIpQFVDMMyyWYFYVlvyBH+3P+yao6x/eTfJKijt6C1B4wmV79gpmTtx9zqXt9Azc2FLji7iPWepRTmGjLOCyveSZ6nxDoqqHFDCmHCNbtF+7FJx1/spFIUxKTXDPHLLrAB3Y4kWNxH8jg8dxHj9rjZtAQbY6s289si9CmQNcuZPW3oq4IhhziA1xGBCnUsBFsDls25r2yvMyMzNCTtq2KsVcCKzFRBdU6RBnxdr+hGp44dpJgYpJ+J4Hk8sILVVC1FfFcMpx5w1y+2MOSv+NGc0/fJz/XB+PxF8No57AdRi5/ffoMN631+nONZ0nC0owPZDWTxqJIMGx3OlHr/T6veDQNHbyB3kVWGnRmnUZAyF2WdZR7Hu60ZnpXlDb3cOGa+qBYvPWWy0AmoAUbrdNEBW+urxI2UNN2Wi0OHt819K8i8s6nLBQnP/RIrcbcfatnxKhg0HA8HSJDIiuaJX25wNfx2nAVfVBF2W6+uRstbf9Xu65fvsIRqz/SAjG3mRCNGPUNZMG5vcnjpIrRR/AMfnLL700khmJTlizx8h+SnuENhyRWCMvaW47WXGlYZde3hW2FUNhM8IzJMLr62xgE9PRxkPrM1dSt08aXlOD33NPduWaLtUhUBo9ovqT+VfgSGp50qTiqeTlNtlngXGg8HCOCQeslkPIpUPB5lWhsUpih23zaPjFDZBAUCddcjh4rAUDqolxIZShvQqekNkV9RMxCLIKtKf4HVk7gFC3vIkjzgg05Bp/HFlg6YgYvVolPuBcCuBIk159dAChy8bNXxqodR8+GYOyMZgwjBpApLmZigga+sA6DvGXhAUejdM9kAP6crIAfujmfkhbGIcvNO5doTXvYR3dxtcd/GGlJITUu0GlyYCvlocJ7QWFH39iGuyFjVBpDHWT8l0QBrjfhcILsCgB0jOXM0VY7fndNpm0kFX4x3MKt+0W8/pO
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      creationTimestamp: null
      labels:
        credential.azimuth-cloud.io/provider: openstack
      name: default-openstack-credential
      namespace: az-test-tenancy
